dataset: "kids_speech"

path:
  corpus_path: "./data/kids_speech"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/kids_speech"
  preprocessed_path: "./preprocessed_data/kids_speech"

preprocessing:
  speaker_id: "ahj"
  val_size: 6
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
